#!/usr/bin/env python3
"""Generate all app icons from one design: a red heart centered on a white
rounded card over a green table. Run with the project's Pillow venv:

    /tmp/ftenv/bin/python scripts/gen_icons.py

Outputs:
  web/icon-192.png, web/icon-512.png   (PWA)
  assets/icon.ico                       (Windows)
  assets/icon.icns                      (macOS, via iconutil)
  src/icon_data.h                       (embedded 128px RGBA for SDL_SetWindowIcon)
"""
import math
import os
import subprocess
import tempfile
from PIL import Image, ImageDraw

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
GREEN = (11, 84, 62, 255)
CARD = (248, 246, 240, 255)
RED = (196, 30, 48, 255)


def heart_points(n=512):
    pts = []
    for i in range(n):
        t = 2 * math.pi * i / n
        x = 16 * math.sin(t) ** 3
        # screen y grows downward, so negate: point at the bottom, lobes on top
        y = -(13 * math.cos(t) - 5 * math.cos(2 * t) - 2 * math.cos(3 * t) - math.cos(4 * t))
        pts.append((x, y))
    return pts


def render(size, ss=4):
    N = size * ss
    img = Image.new("RGBA", (N, N), GREEN)
    d = ImageDraw.Draw(img)
    m = 0.13 * N
    d.rounded_rectangle([m, m, N - m, N - m], radius=0.16 * (N - 2 * m), fill=CARD)

    # Center the heart's bounding box within the card (minus padding).
    pad = 0.17 * (N - 2 * m)
    hx0, hy0, hx1, hy1 = m + pad, m + pad, N - m - pad, N - m - pad
    pts = heart_points()
    xs = [p[0] for p in pts]
    ys = [p[1] for p in pts]
    minx, maxx, miny, maxy = min(xs), max(xs), min(ys), max(ys)
    hw, hh = maxx - minx, maxy - miny
    aw, ah = hx1 - hx0, hy1 - hy0
    scale = min(aw / hw, ah / hh)
    offx = hx0 + (aw - hw * scale) / 2 - minx * scale
    offy = hy0 + (ah - hh * scale) / 2 - miny * scale
    poly = [(p[0] * scale + offx, p[1] * scale + offy) for p in pts]
    d.polygon(poly, fill=RED)

    return img.resize((size, size), Image.LANCZOS)


def main():
    web = os.path.join(ROOT, "web")
    assets = os.path.join(ROOT, "assets")
    os.makedirs(assets, exist_ok=True)

    render(192).save(os.path.join(web, "icon-192.png"))
    render(512).save(os.path.join(web, "icon-512.png"))

    # Windows .ico (multi-resolution from a crisp 256 base).
    render(256).save(os.path.join(assets, "icon.ico"),
                     sizes=[(16, 16), (24, 24), (32, 32), (48, 48), (64, 64), (128, 128), (256, 256)])

    # macOS .icns via iconutil.
    with tempfile.TemporaryDirectory() as tmp:
        iconset = os.path.join(tmp, "icon.iconset")
        os.makedirs(iconset)
        for base in (16, 32, 128, 256, 512):
            render(base).save(os.path.join(iconset, f"icon_{base}x{base}.png"))
            render(base * 2).save(os.path.join(iconset, f"icon_{base}x{base}@2x.png"))
        subprocess.run(["iconutil", "-c", "icns", iconset,
                        "-o", os.path.join(assets, "icon.icns")], check=True)

    # Embedded RGBA for SDL_SetWindowIcon (runtime window/taskbar icon).
    icon = render(128).convert("RGBA")
    data = icon.tobytes()
    with open(os.path.join(ROOT, "src", "icon_data.h"), "w") as f:
        f.write("// App icon as 128x128 RGBA (R,G,B,A), generated by scripts/gen_icons.py.\n")
        f.write("#pragma once\n")
        f.write(f"static const int kIconW = 128, kIconH = 128;\n")
        f.write("static const unsigned char kIconRGBA[] = {\n")
        for i in range(0, len(data), 24):
            f.write(",".join(str(b) for b in data[i:i + 24]) + ",\n")
        f.write("};\n")

    print("wrote web/icon-192.png, web/icon-512.png, assets/icon.ico, assets/icon.icns, src/icon_data.h")


if __name__ == "__main__":
    main()
